import type { BuildInput } from '../engine';

/** Neutral settings used as a starting point by tests. */
export function emptySettings(): Omit<BuildInput, 'pages' | 'objectsByPage' | 'assets' | 'sources'> {
  return {
    crops: {},
    textEdits: [],
    ocr: {},
    meta: {
      title: '',
      author: '',
      subject: '',
      keywords: '',
      creator: 'PDFmaster',
      producer: 'PDFmaster 1.0',
    },
    security: {
      enabled: false,
      userPassword: '',
      ownerPassword: '',
      algorithm: 'AES-256',
      allowPrinting: 'all',
      allowCopying: true,
      allowModifying: true,
      allowAnnotating: true,
      allowForms: true,
      allowAccessibility: true,
      allowAssembly: true,
    },
    watermark: {
      enabled: false,
      text: 'CONFIDENTIAL',
      fontSize: 48,
      color: '#ff4a3d',
      opacity: 0.25,
      rotation: 45,
      tile: false,
      pages: 'all',
      bold: true,
    },
    headerFooter: {
      enabled: false,
      header: { left: '', center: '', right: '' },
      footer: { left: '', center: '', right: '' },
      fontSize: 9,
      color: '#444444',
      margin: 36,
      firstPageDifferent: false,
    },
    pageNumbers: {
      enabled: false,
      position: 'bottom-center',
      startAt: 1,
      fontSize: 9,
      color: '#444444',
      margin: 28,
      prefix: '',
      suffix: '',
    },
    bates: {
      enabled: false,
      prefix: '',
      suffix: '',
      startAt: 1,
      digits: 6,
      position: 'bottom-right',
      fontSize: 9,
      color: '#222222',
      margin: 28,
    },
    bookmarks: [],
    attachments: [],
    options: {},
  };
}
